# Generated by Django 6.0.3 on 2026-05-28 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='price',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Стоимость'),
        ),
    ]
