# Generated by Django 6.0.3 on 2026-05-28 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_alter_lead_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Стоимость'),
        ),
    ]
